### ISSUE TITLE
Design and implement an all-in-one report

### ISSUE THREAD

**Issue by brandonlockhart** [sfu-db/dataprep#116]
Given a dataset, run all (or many) of the plot functions, and output the visualizations into a nicely formatted html file. This will be similar to pandas-profiling, the main differences being a larger variety of interaction plots and the tooltip. The current plan is to not include descriptive statistics.

- [ ] Create a low-fidelity mockup
- [ ] Get feedback about the mockup from the DataPrep team
- [ ] Implement the report
- [ ] Test

**Comment by jnwang** [comment]
Here is one related paper. It tells you how different R libs design a report. 

https://arxiv.org/pdf/1904.02101.pdf
