### ISSUE TITLE
Enhance eda.plot_missing: Bar Chart

### ISSUE THREAD

**Issue by Waterpine** [sfu-db/dataprep#181]
**Task**: add a Bar chart to plot_missing(df) (one of the tasks of #168)

We have to add a tag named bar chart like missingno.
The link of missingno: https://github.com/ResidentMario/missingno.
The data could be extracted from the spectrum figure.

Time: 2020.6.22 - 2020.6.28

@Sanjana12111994

- [x] Make the bar chart a stacked bar chart with legend aside.
- [x] Move the bar chart at the beginning of the panels.
- [x] Capitalize the chart titles.

**Comment by Sanjana12111994** [comment]
Made the bar charts a stacked bar chart with the legend.
 Moved the bar chart at the beginning of the panels.
 Capitalized the chart titles.
Please find the image for reference![bar_chart.png](https://images.zenhubusercontent.com/5ef4f103ae27ac20570c9c1b/2b9b4e4c-5fd9-4e3d-9938-b4f8a840738f)

Let me know if any further changes are required.

**Comment by dovahcrow** [comment]
I'll merge the code for now but this issue cannot be closed. Some more work should be done to ensure the code quality before closing the issue:
- [ ] missing_spectrum is not used. It would be better to remove it.
- [ ] missing_spectrum_tabs is reading the data out of dask, which is not efficient.
- [ ] missing_spectrum_tabs should be renamed to `missing_tabs` since it is not just a spectrum anymore.
