### ISSUE TITLE
Data Connector: Add more websites

### ISSUE THREAD

**Issue by peiwangdb** [sfu-db/dataprep#209]
Add configuration files for the following websites:

- [ ] IMDB (Movies Database)
The most popular and sought after movie database API is the perfect solution for a developer in need of an API to retrieve IMDb data.
 
- [ ] Sky Scanner
A metasearch engine that provides travel data for flights, hotels, car rentals etc. Skyscanner aggregates travel and flight data so users don’t have to go to multiple sites to check each individual flight plan or price. The Skyscanner API allows access to this aggregated travel data to retrieve the cheapest flight dates and quotes, browse flight routes, and much more.

- [x] Open Weather API
Weather Data from any location for free of cost. I have personally used this and have seen a lot of my friends use this to extract weather information.

- [x] MusiXmatch
World’s largest lyrics database with over 50 million active users and over 14 million lyrics. The musiXmatch API grants developers access to this music, album and lyrics data.

- [x] YouTube:
Undoubtedly the most popular website for Video content. The API allows users to search for videos matching specific search terms, topics, locations, publication dates, and much more.

- [ ] Deezer:
The Deezer API allows developers access into Deezer’s massive music database of over 30 million tracks and playlists.

- [x] Spoonacular:
The Spoonacular API is the ultimate Recipe, Food and Nutrition database all rolled up into a single API, making it “the only Food API you’ll ever need.” With Spoonacular, you’ll get access to over 365,000 recipes and 86,000 food products.

- [ ] Breaking News (By MyAllies):
RESTful API that provides financial news data such as real-time news feeds, company news (about a specific company), and company details (by company ticker symbol).

Plus Slack API + Two Fintech APIs.

Keep and upload the example notebook if possible for reproducibility.

**Comment by peiwangdb** [comment]
@kla55 please follow here, thanks!

**Comment by kla55** [comment]
I will take a look at spoonacular and another fintech api

**Comment by kla55** [comment]
Completed Spoonacular.

**Comment by nick-zrymiak** [comment]
I'll create a config file and example for MusiXmatch.
