### ISSUE TITLE
Generator Improvements

### ISSUE THREAD

**Issue by dovahcrow** [sfu-db/dataprep#361]
- [ ] Split format support (we haven't met a website has this format).
- [ ] Flatten table (fields can have a nested structure).
- [ ] XML response support (Only DBLP returns XML. However it actually also has JSON return).

**Comment by dovahcrow** [comment]
@jnwang @peiwangdb @wangxiaoying @liuyejia Do you guys have other suggestions on the improvements?
