### ISSUE TITLE
EDA: polish UI

### ISSUE THREAD

**Issue by jinglinpeng** [sfu-db/dataprep#366]
- [ ] Apply the new layout to all the plots.
- [ ] Learn the visualizations from commercial products like PowerBI, Tableau and Trifacta and polish our visualizations.
- [ ] For plot_missing(df, x), change the tab-based layout to grid-based layout like the layout in plot(df).
